In [2]:
import numpy as np

#Reshape
data_1d = np.array([900, 30, 1000, 50, 1100, 70])
data_2d = data_1d.reshape(3,2)
print("Reshaped to 3x2:")
print(data_2d)

Reshaped to 3x2:
[[ 900   30]
 [1000   50]
 [1100   70]]


In [3]:
flat = data_2d.flatten()
print("\nFlattened:", flat)


Flattened: [ 900   30 1000   50 1100   70]


In [4]:
#Transpose
print("\nTransposed:")
print(data_2d.T)


Transposed:
[[ 900 1000 1100]
 [  30   50   70]]


In [5]:
# Stack arrays
temps = np.array([900, 1000, 1100])
diameters = np.array([30, 50, 70])
heights = np.array([300, 500, 700])

# Vertical stack(rows)
vstack = np.vstack([temps, diameters, heights])
print("\nVertical stack:")
print(vstack)


Vertical stack:
[[ 900 1000 1100]
 [  30   50   70]
 [ 300  500  700]]


In [6]:
# Column stack (easier for data)
cstack = np.column_stack([temps, diameters, heights])
print("\nColumn stack:")
print(cstack)


Column stack:
[[ 900   30  300]
 [1000   50  500]
 [1100   70  700]]


In [7]:
# Concatenate
batch1 = np.array([[900, 30], [1000, 50]])
batch2 = np.array([[1100, 70], [1050, 55]])
combined = np.concatenate([batch1, batch2], axis=0)
print("\nConcatenated:")
print(combined)


Concatenated:
[[ 900   30]
 [1000   50]
 [1100   70]
 [1050   55]]


In [8]:
# Add dimension
temps_col = temps[:, np.newaxis]
print("\n1D shape:", temps.shape)
print("Column shape:", temps_col.shape)


1D shape: (3,)
Column shape: (3, 1)


In [ ]:
temps = np.array([700, 800, 900, 1000, 1100, 1200, 1300])
diameters = np.array([30, 40, 50, 60, 70, 80, 90])
heights = np.array([300, 350, 400, 450, 500, 550, 700])
cstack = np.column_stack([temps, diameters, heights])
print('\nStacked columns:')
print(cstack)