In [3]:
import numpy as np

#1D indexing
temps = np.array([900, 950, 1000, 1050, 1100])
print("First element:", temps[0])
print("Last element:", temps[-1])
print("First three:", temps[0:3])
print("Every other:", temps[::2])

First element: 900
Last element: 1100
First three: [ 900  950 1000]
Every other: [ 900 1000 1100]


In [9]:
data = np.array ([
    [900, 30, 300],
    [1000, 50, 500],
    [1100, 70, 700],
    [1050, 55, 550]
])

print("\nElement [1,2]:", data[1,2])
print("\nFirst row:", data[0])
print("All diameters(col1):", data[:,1])
print("First two rows:", data[0:2])


Element [1,2]: 500

First row: [900  30 300]
All diameters(col1): [30 50 70 55]
First two rows: [[ 900   30  300]
 [1000   50  500]]


In [11]:
#Boolean indexing
high_temp = data[:,0]>1000
print("\nHigh temp experiments:")
print(data[high_temp])


High temp experiments:
[[1100   70  700]
 [1050   55  550]]


In [12]:
#Multiple conditions
good = (data[:, 0] > 950) & (data[:, 1] > 40)
print("\nGood conditions (T>950 & D>40):")
print(data[good])


Good conditions (T>950 & D>40):
[[1000   50  500]
 [1100   70  700]
 [1050   55  550]]


In [ ]:
#Where function
large_idx = np.where(data[:, 1] > 50)
print("\nIndices where diameter > 50:", large_idx[0])


Indices where diameter > 50: [2 3]


In [ ]:
#Modify arrays
modified = data.copy()
modified[modified[:, 1] < 50, 1] = 50
print("\nAfter setting min diameter to 50:")
print(modified)