In [2]:
import numpy as np

#Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot = np.dot(a, b)
print("Dot product:", dot)
print("Alternative:", a @ b)

Dot product: 32
Alternative: 32


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A @ B
print("\nMatrix multiply:")
print(result)


Matrix multiply:
[[19 22]
 [43 50]]


In [4]:
# Determinant
det = np.linalg.det(A)
print("\nDeterminant:", det)


Determinant: -2.0000000000000004


In [5]:
# Inverse
inv = np.linalg.inv(A)
print("\nInverse:")
print(inv)


Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
# Verify: A @ inv = Identity
identity = A @ inv
print("\nA @ inv (should be I):")
print(identity.round(4))


A @ inv (should be I):
[[1. 0.]
 [0. 1.]]


In [7]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors")
print(eigenvectors)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [8]:
# Solve linear system: Ax = b
A = np.array([[2,1],[1,3]])
b = np.array([10, 15])
x = np.linalg.solve(A, b)
print("\nSolution to Ax=b:", x)


Solution to Ax=b: [3. 4.]


In [9]:
# Vector norm (magnitude)
vector = np.array([3, 4])
magnitude = np.linalg.norm(vector)
print("\nVector magnitude", magnitude)


Vector magnitude 5.0


In [ ]:
# Create a 3x3 matrix representing lattice vectors. Calculate its determinant 
# (volume) and inverse. Verify the inverse is correct.

A = np.array([[1,2,3],[4,5,6],[7,8,1]])
det = np.linalg.det(A)
print("\nDeterminant:", det)

#inv
inv = np.linalg.inv(A)
print("\nInverse:", inv)

#verify
identity = A @ inv
print("\nA @ inv = \n", identity)

#check
print("\nIs it identity? ->", np.allclose(identity, np.eye(3)))


Determinant: 23.999999999999993

Inverse: [[-1.79166667  0.91666667 -0.125     ]
 [ 1.58333333 -0.83333333  0.25      ]
 [-0.125       0.25       -0.125     ]]

A @ inv = 
 [[ 1.00000000e+00  1.66533454e-16  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [-8.32667268e-17  5.55111512e-17  1.00000000e+00]]
