In [1]:
import numpy as np

#Arrays of zeros
growth_data = np.zeros(10)
print("Zeros:", growth_data)

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
temperatures = np.array([900, 950, 1000, 1050, 1100])
diameters = np.array([30, 45, 50, 55, 70])

print("Temperatures:", temperatures)
print("Type:", type(temperatures))
print("Data type:", temperatures.dtype)
print("Shape:", temperatures.shape)
print("Size:", temperatures.size)

Temperatures: [ 900  950 1000 1050 1100]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (5,)
Size: 5


In [13]:
data=np.array([
    [900, 1e-5, 30, 300],
    [1000, 2e-5, 50, 500],
    [1100, 3e-5, 70, 700]
])

print("\nExperimental data:")
print(data)
print("Shape(rows, cols):", data.shape)
print("First experiment:", data[0])
print("All temperatures:", data[:, 0])
print("All diameters:", data[:, 2])


Experimental data:
[[9.0e+02 1.0e-05 3.0e+01 3.0e+02]
 [1.0e+03 2.0e-05 5.0e+01 5.0e+02]
 [1.1e+03 3.0e-05 7.0e+01 7.0e+02]]
Shape(rows, cols): (3, 4)
First experiment: [9.e+02 1.e-05 3.e+01 3.e+02]
All temperatures: [ 900. 1000. 1100.]
All diameters: [30. 50. 70.]


In [19]:
data = np.array([
    [700, 500, 30],
    [800, 600, 40],
    [900, 700, 50]
])

print(np.mean(data, axis=0))

print(data)
print("\nShape:", data.shape)

column_means = np.mean(data, axis=0)
print("\nColumn means (avg of each parameter):")
print("Average temp:", column_means[0], "Celcius")
print("Average time:", column_means[1], "minutes")
print("Average diameter", column_means[2], "nm")

print("\n---Alternative Method ---")
avg_temp = data[:, 0].mean()
avg_time = data[:,1].mean()
avg_diam = data[:,2].mean()
print(f"Average temperature: {avg_temp} Celcius")
print(f"Time:{avg_time} min")
print(f"Diameter:{avg_diam} nm")

[800. 600.  40.]
[[700 500  30]
 [800 600  40]
 [900 700  50]]

Shape: (3, 3)

Column means (avg of each parameter):
Average temp: 800.0 Celcius
Average time: 600.0 minutes
Average diameter 40.0 nm

---Alternative Method ---
Average temperature: 800.0 Celcius
Time:600.0 min
Diameter:40.0 nm


In [14]:
import numpy as np

#Create experimental data

experiments = np.array ([
    [700, 500, 30],
    [800, 600, 40],
    [900, 700, 50],
    [850, 650, 45],
    [750, 550, 35]
])

print("===Full Analysis===\n")

#Mean of each paramenter(column)
means = experiments.mean(axis=0)
print("Parameter Means:")
print(f" Temperature: {means[0]:.1f} Celcius ")
print(f" Time: {means[1]:.1f} min")
print(f" Diameter {means[2]:.1f} nm")

stds = experiments.std(axis=0)
print("\nParamenter Std Deviations:")
print(f" Temperature: {stds[0]:.1f} Degrees")
print(f" Time {stds [1]:.1f} min")
print(f" Diameter: {stds[2]:.1f} nm")

#min and max
mins = experiments.min(axis=0)
maxs = experiments.max(axis=0)
print("\nParameter Ranges:")
print(f" Temperature: {mins[0]} - {maxs[0]} Degrees")
print(f" Time: {mins[1]} - {maxs[1]} min")
print(f" Diameter: {mins[2]}-{maxs[2]} nm")

#Summary table
print("\n===Summary Table===")
print("Parameter | Mean | Std | Min | Max")
print("-" * 50)
print(f"Temperature | {means[0]:.1f} | {stds[0]:.1f} | {mins[0]:.0f} | {maxs[0]:.0f}")
print(f"Time         | {means[1]:.1f}  | {stds[1]:.1f} | {mins[1]:.0f}  | {maxs[1]:.0f}")
print(f"Diameter     | {means[2]:.1f}  | {stds[2]:.1f}  | {mins[2]:.0f}   | {maxs[2]:.0f}")

===Full Analysis===

Parameter Means:
 Temperature: 800.0 Celcius 
 Time: 600.0 min
 Diameter 40.0 nm

Paramenter Std Deviations:
 Temperature: 70.7 Degrees
 Time 70.7 min
 Diameter: 7.1 nm

Parameter Ranges:
 Temperature: 700 - 900 Degrees
 Time: 500 - 700 min
 Diameter: 30-50 nm

===Summary Table===
Parameter | Mean | Std | Min | Max
--------------------------------------------------
Temperature | 800.0 | 70.7 | 700 | 900
Time         | 600.0  | 70.7 | 500  | 700
Diameter     | 40.0  | 7.1  | 30   | 50


In [15]:
import numpy as np

#Arrays of zeros

growth_data = np.zeros(10)
print("Zeros:", growth_data)

#Arrays of ones
mask = np.ones(5)
print("Ones:", mask)

#Range of values
time = np.arange(0, 60, 5)
print("Time points:", time)

#Evenly spaced values (start, stop, count)
temps = np.linspace(900, 1100, 5) #5 temps from 900 to 1100
print("Temperature range:", temps)

#Idnetity matrix
indentity = np.eye(3)
print("\nIdentity matrix:")
print(indentity)

#Random arrays
np.random.seed(42)
random_diameters = np.random.uniform(40, 60, 10)
print("\nRandom diameters:", random_diameters.round(2))

#Normal distribution (mean=50, std=5)
gaussian_sizes = np.random.normal(50, 5, 100)
print("Gaussian mean:", gaussian_sizes.mean().round(2))
print("Gaussian std:", gaussian_sizes.std().round(2))

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Time points: [ 0  5 10 15 20 25 30 35 40 45 50 55]
Temperature range: [ 900.  950. 1000. 1050. 1100.]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random diameters: [47.49 59.01 54.64 51.97 43.12 43.12 41.16 57.32 52.02 54.16]
Gaussian mean: 49.23
Gaussian std: 4.5


In [38]:
import numpy as np

#Evenly spaced temperatures
temperatures = np.linspace(800, 1200, 20)

#Random diameters
diameters = np.random.normal(50,10,20)

print("temperatures:", temperatures)
print("diameters:", diameters)

print("===Temperatures===")
print("Values:", temperatures.round(1))
print("Min:", temperatures.min(), "Celcius")
print("Max:", temperatures.max(), "Celcius")
print("Step size:", (temperatures[1] - temperatures[0]).round(2), "Celcius")

print("\n===Diameters===")
print("Values:", diameters.round(2))
print("Mean:", diameters.mean().round(2),"nm")
print("Std Dev:", diameters.std().round(2), "nm")
print("Min:", diameters.min().round(2), "nm")
print("Max:", diameters.max().round(2), "nm")

#Verify the distribution
print("\n===Verification===")
print("Target mean: 50 nm")
print("Actual mean:", diameters.mean().round(2), "nm")
print("Target std: 10nm")
print("Actual std:", diameters.std().round(2), "nm")
print("Close enought? ✓" if abs(diameters.mean()-50) < 5 else "Return needed")

temperatures: [ 800.          821.05263158  842.10526316  863.15789474  884.21052632
  905.26315789  926.31578947  947.36842105  968.42105263  989.47368421
 1010.52631579 1031.57894737 1052.63157895 1073.68421053 1094.73684211
 1115.78947368 1136.84210526 1157.89473684 1178.94736842 1200.        ]
diameters: [44.45366168 54.7514466  42.24724779 62.80619286 49.23843807 54.38436561
 51.6918942  40.22359313 44.28814061 65.21222894 54.54409755 37.13435313
 42.58277308 55.75901323 60.6806082  57.88062449 63.54463781 56.75514568
 49.18896733 53.102245  ]
===Temperatures===
Values: [ 800.   821.1  842.1  863.2  884.2  905.3  926.3  947.4  968.4  989.5
 1010.5 1031.6 1052.6 1073.7 1094.7 1115.8 1136.8 1157.9 1178.9 1200. ]
Min: 800.0 Celcius
Max: 1200.0 Celcius
Step size: 21.05 Celcius

===Diameters===
Values: [44.45 54.75 42.25 62.81 49.24 54.38 51.69 40.22 44.29 65.21 54.54 37.13
 42.58 55.76 60.68 57.88 63.54 56.76 49.19 53.1 ]
Mean: 52.02 nm
Std Dev: 7.96 nm
Min: 37.13 nm
Max: 65.21 nm

==

In [10]:
import numpy as np

np.random.seed(42)

#Your solution
temperatures = np.linspace(800, 1200, 20)
diameters = np.random.normal(50, 10, 20)

#Now let's do something useful with this data!

#1. Combine into experimental dataset
experiments = np.column_stack([temperatures, diameters])
print("Combined Data(first 5 experiments):")
print(experiments[:5])

#2. Simulate heights based on temperature (highter temp -> taller)
#Simple model: height increases with temperature
heights = 5 * (temperatures - 800) + np.random.normal(0, 20, 20)
print("\nSimulated Heights:", heights.round(1))

#3. Calculate aspect ratios
aspect_ratios = heights / diameters
print("\nAspect Ratios:", aspect_ratios.round(2))

#4. Find optimal conditions
best_idx = np.argmax(aspect_ratios)
print("\n=== Best Experiment ===")
print(f"Index:{best_idx}")
print(f"temperature: {temperatures[best_idx]:.1f} Celcius")
print(f"diameter:{diameters[best_idx]:.2f} nm")
print(f"Height:{heights[best_idx]:.2f} nm")
print(f"Aspect Ratio:{aspect_ratios[best_idx]:.2f}")

#5. Filter good nanowires (AR > 30)
good_nanowires = aspect_ratios > 30
print(f"\n{good_nanowires.sum()} out of {len(aspect_ratios)} have AR > 30")
print("Good temperatures:", temperatures[good_nanowires].round(1))


Combined Data(first 5 experiments):
[[800.          54.96714153]
 [821.05263158  48.61735699]
 [842.10526316  56.47688538]
 [863.15789474  65.23029856]
 [884.21052632  47.65846625]]

Simulated Heights: [  29.3  100.7  211.9  287.3  410.2  528.5  608.6  744.4  830.1  941.5
 1040.6 1194.9 1262.9 1347.3 1490.1 1554.5 1688.4 1750.3 1868.2 2003.9]

Aspect Ratios: [ 0.53  2.07  3.75  4.4   8.61 11.09  9.25 12.91 18.32 16.99 22.94 26.35
 24.09 43.65 45.5  35.03 42.35 32.94 45.65 55.86]

=== Best Experiment ===
Index:19
temperature: 1200.0 Celcius
diameter:35.88 nm
Height:2003.94 nm
Aspect Ratio:55.86

7 out of 20 have AR > 30
Good temperatures: [1073.7 1094.7 1115.8 1136.8 1157.9 1178.9 1200. ]


In [13]:
import numpy as np

temperatures = np.linspace(700, 1300, 50)
pressures = np.linspace(1e-6, 1e-4, 50)
diameters = np.random.normal(55, 8, 50)
heights = np.random.normal(550, 80, 50)

#print(temperatures)
#print(pressures)
#print(diameters)
#print(heights)

matrix = np.column_stack([temperatures, pressures, diameters, heights])
print(matrix)
print(matrix.shape)

print(f'Mean: {matrix.mean(axis=0)}')
print(f'Standard deviation:{matrix.std(axis=0)}')
print(f'Minimum value:{matrix.min(axis=0)}')
print(f'Maximum value:{matrix.max(axis=0)}')
np.savetxt("gan_experiments.csv", 
           matrix, 
           delimiter=",", 
           header="Temperature,Pressure,Diameter,Height", 
           comments="In this csv file you can find random values for gan growth results"
           )



[[7.00000000e+02 1.00000000e-06 5.57289226e+01 4.45831458e+02]
 [7.12244898e+02 3.02040816e-06 5.39719176e+01 4.37194423e+02]
 [7.24489796e+02 5.04081633e-06 5.08623945e+01 4.42204936e+02]
 [7.36734694e+02 7.06122449e-06 4.44299471e+01 6.18245465e+02]
 [7.48979592e+02 9.08163265e-06 5.63771417e+01 5.96609567e+02]
 [7.61224490e+02 1.11020408e-05 4.86452096e+01 5.02274492e+02]
 [7.73469388e+02 1.31224490e-05 6.08182766e+01 5.43363813e+02]
 [7.85714286e+02 1.51428571e-05 4.91638758e+01 6.51720463e+02]
 [7.97959184e+02 1.71632653e-05 5.97422267e+01 5.81698263e+02]
 [8.10204082e+02 1.91836735e-05 4.23604847e+01 5.40588421e+02]
 [8.22448980e+02 2.12040816e-05 5.97341187e+01 5.61407157e+02]
 [8.34693878e+02 2.32244898e-05 5.01321626e+01 5.25631644e+02]
 [8.46938776e+02 2.52448980e-05 4.35557470e+01 6.50328051e+02]
 [8.59183673e+02 2.72653061e-05 5.29352798e+01 5.32725894e+02]
 [8.71428571e+02 2.92857143e-05 6.48750077e+01 4.97155491e+02]
 [8.83673469e+02 3.13061224e-05 5.30668871e+01 6.843906

In [6]:
import numpy as np

# Temperature conversion (vectorized!)

temps_c = np.array([900, 1000, 1100, 1200])
temps_k = temps_c + 273.15 #Converts all at once
print("Celsius:", temps_c)
print("Kelvin:", temps_k)

# Element-wise operations
diameters = np.array([30, 50, 70])
heights = np.array([300, 500, 700])
aspect_ratios = heights / diameters
print("\nAspect ratios:", aspect_ratios)

#Mathematical functions
radii = diameters / 2
volumes = np.pi * radii**2 * heights
print("Volumes (nm3):", volumes.round(0))

#Boolean operations 
large_nanowires = diameters > 40
print("\nDiameter > 40nm:", large_nanowires)

#Boolean indexing (filter)
large_diameters = diameters[diameters > 40]
print("Large diameters only:", large_diameters)

#Universal functions
temps = np.array([900, 1000, 1100])
exp_factor = np.exp(-1.5 / (temps / 1000))
print("\nExp factors:", exp_factor.round(4))

Celsius: [ 900 1000 1100 1200]
Kelvin: [1173.15 1273.15 1373.15 1473.15]

Aspect ratios: [10. 10. 10.]
Volumes (nm3): [ 212058.  981748. 2693916.]

Diameter > 40nm: [False  True  True]
Large diameters only: [50 70]

Exp factors: [0.1889 0.2231 0.2557]
